project:
  type: website

website:
  title: "Atomic Insights"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: terms.qmd
        text: Glossary
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css